### ISSUE TITLE
/etc/openvpn/vpnfailsafe.sh:79: `echo -e "${domains/ /search }\n${ns// /$'\n'nameserver }"|resolvconf -xa "$dev"' returned 99

### ISSUE THREAD

**Issue by sash322** [wknapik/vpnfailsafe#20]
When running openvpn /etc/openvpn/myconf.conf got this 
...
Fri Sep 22 17:25:18 2017 /etc/openvpn/vpnfailsafe.sh tun0 1500 1602 10.8.0.2 255.255.255.0 init
resolvconf: Error: Command not recognized
Usage: resolvconf (-d IFACE|-a IFACE|-u|--enable-updates|--disable-updates|--updates-are-enabled)
/etc/openvpn/vpnfailsafe.sh:79: `echo -e "${domains/ /search }\n${ns// /$'\n'nameserver }"|resolvconf -xa "$dev"' returned 99
Fri Sep 22 17:25:18 2017 WARNING: Failed running command (--up/--down): external program exited with error status: 99

**Comment by wknapik** [comment]
Hi @sash322, that looks like [this report](https://github.com/wknapik/vpnfailsafe/issues/13#issuecomment-314678151). You're using a resolvconf version, that's >2 years old and doesn't support the -x switch. Upgrading to a newer version should _resolve_ the problem ;] Depending on your distro, the package might have different names - openresolv, resolvconf, etc.

**Comment by sash322** [comment]
Ty for response. Fixed that problem by installing last version of openresolv with this guide https://gist.github.com/uzantonomon/5489a4d9fe4caf813f45bf4bde3a1ffe
