### ISSUE TITLE
resolvconf error

### ISSUE THREAD

**Issue by Daniel-GabrielN** [wknapik/vpnfailsafe#21]
resolvconf: Error: Command not recognized
Usage: resolvconf (-d IFACE|-a IFACE|-u|--enable-updates|--disable-updates|--updates-are-enabled)
/etc/openvpn/vpnfailsafe.sh:79: `echo -e "${domains/ /search }\n${ns// /$'\n'nameserver }"|resolvconf -xa "$dev"' returned 99
Tue Oct 24 22:47:40 2017 us=8878 WARNING: Failed running command (--up/--down): external program exited with error status: 99
Tue Oct 24 22:47:40 2017 us=8905 Exiting due to fatal error

I get this error on Linux mint, any idea why?

Regards,
Dan

**Comment by wknapik** [comment]
Hi Dan. Your resolvconf version is too old. This was first reported [here](https://github.com/wknapik/vpnfailsafe/issues/13#issuecomment-314678151) and then [here](https://github.com/wknapik/vpnfailsafe/issues/20). I have no idea why some distros have not updated resolvconf in >2 years. Anyway - updating to a more recent resolvconf/openresolv version will fix the error.

**Comment by Daniel-GabrielN** [comment]
Thank you for your quick reply, I will update my resolvconf.
