### ISSUE TITLE
Cannot ping VPN's nameserver

### ISSUE THREAD

**Issue by pensionars** [wknapik/vpnfailsafe#22]
With the script active it adds the correct nameservers to resolv.conf but it seems the rules added to iptables stop me from even pinging the nameservers provided by the VPN. I would love to add my iptables but I am afraid of putting my ip so openly on the internet, maybe I can send it to you privately?

**Comment by wknapik** [comment]
Hi @ansiiis,

To debug this properly, I'd need the output of the following commands:
- `ip route`
- `iptables -S`
- `resolvconf -l`
- `cat /etc/resolv.conf`

You can contact me at wmknapik at gmail com to provide the info. Feel free to obscure anything you'd rather not share, though I would need at least the private IPs to remain intact (or modified in a consistent way).

I suspect that this is not about the firewall, but rather about the routing. My guess is that your VPN provider is not respecting their own netmask and you have routing set up properly, but the DNS server, exposed at a private IP, is actually outside the network carved out by this netmask. I've seen that with one provider before. You can test for this by running `ip route get your_dns_server_ip`. This will tell you how traffic to that IP would be routed. If it would be routed via any device other than the tunnel, then my suspicion is confirmed.

Anyhow, I'll be waiting for further info from you.

**Comment by wknapik** [comment]
I just realized I never actually said, that the command outputs I listed should be collected after the VPN connection is established and vpnfailsafe gets executed.

**Comment by ansiiis** [comment]
sending this to your gmail in 5-10 minutes

**Comment by pensionars** [comment]
sending this to your gmail in 5-10 minutes but it looks to me it is routed through the tunnel
EDIT. I just realized I do not have your gmail address.

**Comment by wknapik** [comment]
Hi @ansiiis. I didn't notice the edit. The email address is above, in my initial response. I just skipped the "@" to avoid getting it scraped too easily. Feel free to use PGP to encrypt your message, if you like. You can get my public key by running `gpg --keyserver hkp://keys.gnupg.net --recv-key 2CF9B98E7CF8679B8D3F237ED5129D34A38CC133`.

**Comment by wknapik** [comment]
Hi @ansiiis. You never got back to me over email. Since it's been 1.5 months since last contact, I assume this issue is no longer relevant. Closing now, but if you ever get in touch, we can reopen.
