### ISSUE TITLE
pi@raspberrypi:~ $ curl ipinfo.io/ip curl: (6) Could not resolve host: ipinfo.io

### ISSUE THREAD

**Issue by ghost** [wknapik/vpnfailsafe#30]
Fresh install, works fine without vpnfailsafe, whenever I run it with vpnfailsafe I get: 
`pi@raspberrypi:~ $ curl ipinfo.io/ip curl: (6) Could not resolve host: ipinfo.io`
log: 
`root@raspberrypi:~# sudo openvpn --config /etc/openvpn/default.conf
Wed Apr 18 01:07:22 2018 Unrecognized option or missing or extra parameter(s) in /etc/openvpn/default.conf:20: block-outside-dns (2.4.0)
Wed Apr 18 01:07:22 2018 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
Wed Apr 18 01:07:22 2018 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Wed Apr 18 01:07:22 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Apr 18 01:07:22 2018 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Apr 18 01:07:22 2018 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Apr 18 01:07:22 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]35.196.104.252:1194
Wed Apr 18 01:07:22 2018 Socket Buffers: R=[163840->163840] S=[163840->163840]
Wed Apr 18 01:07:22 2018 UDP link local: (not bound)
Wed Apr 18 01:07:22 2018 UDP link remote: [AF_INET]35.196.104.252:1194
Wed Apr 18 01:07:22 2018 TLS: Initial packet from [AF_INET]35.196.104.252:1194, sid=053647db f02a61dd
Wed Apr 18 01:07:22 2018 VERIFY OK: depth=1, CN=cn_triZgPlvbe8lMIUF
Wed Apr 18 01:07:22 2018 Validating certificate key usage
Wed Apr 18 01:07:22 2018 ++ Certificate has key usage  00a0, expects 00a0
Wed Apr 18 01:07:22 2018 VERIFY KU OK
Wed Apr 18 01:07:22 2018 Validating certificate extended key usage
Wed Apr 18 01:07:22 2018 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Apr 18 01:07:22 2018 VERIFY EKU OK
Wed Apr 18 01:07:22 2018 VERIFY X509NAME OK: CN=server_GizGQKWqXhHCzsNt
Wed Apr 18 01:07:22 2018 VERIFY OK: depth=0, CN=server_GizGQKWqXhHCzsNt
Wed Apr 18 01:07:23 2018 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES128-GCM-SHA256, 3072 bit RSA
Wed Apr 18 01:07:23 2018 [server_GizGQKWqXhHCzsNt] Peer Connection Initiated with [AF_INET]35.196.104.252:1194
Wed Apr 18 01:07:24 2018 SENT CONTROL [server_GizGQKWqXhHCzsNt]: 'PUSH_REQUEST' (status=1)
Wed Apr 18 01:07:24 2018 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 9.9.9.9,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.5 255.255.255.0'
Wed Apr 18 01:07:24 2018 OPTIONS IMPORT: timers and/or timeouts modified
Wed Apr 18 01:07:24 2018 OPTIONS IMPORT: --ifconfig/up options modified
Wed Apr 18 01:07:24 2018 OPTIONS IMPORT: route options modified
Wed Apr 18 01:07:24 2018 OPTIONS IMPORT: route-related options modified
Wed Apr 18 01:07:24 2018 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Apr 18 01:07:24 2018 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Wed Apr 18 01:07:24 2018 Data Channel Encrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Apr 18 01:07:24 2018 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Wed Apr 18 01:07:24 2018 Data Channel Decrypt: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Apr 18 01:07:24 2018 ROUTE_GATEWAY 192.168.1.1/255.255.255.0 IFACE=eth0 HWADDR=b8:27:eb:f1:f9:09
Wed Apr 18 01:07:24 2018 TUN/TAP device tun1 opened
Wed Apr 18 01:07:24 2018 TUN/TAP TX queue length set to 100
Wed Apr 18 01:07:24 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Wed Apr 18 01:07:24 2018 /sbin/ip link set dev tun1 up mtu 1500
Wed Apr 18 01:07:24 2018 /sbin/ip addr add dev tun1 10.8.0.5/24 broadcast 10.8.0.255
Wed Apr 18 01:07:24 2018 /etc/openvpn/vpnfailsafe.sh tun1 1500 1569 10.8.0.5 255.255.255.0 init
Too few arguments.
Too few arguments.
Wed Apr 18 01:07:24 2018 /sbin/ip route add 35.196.104.252/32 via 192.168.1.1
RTNETLINK answers: File exists
Wed Apr 18 01:07:24 2018 ERROR: Linux route add command failed: external program exited with error status: 2
Wed Apr 18 01:07:24 2018 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
RTNETLINK answers: File exists
Wed Apr 18 01:07:24 2018 ERROR: Linux route add command failed: external program exited with error status: 2
Wed Apr 18 01:07:24 2018 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
RTNETLINK answers: File exists
Wed Apr 18 01:07:24 2018 ERROR: Linux route add command failed: external program exited with error status: 2
Wed Apr 18 01:07:24 2018 Initialization Sequence Completed`

original iptables 
```
sudo iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
sudo iptables -A FORWARD -i tun0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i wlan0 -o tun0 -j ACCEPT
```

**Comment by wknapik** [comment]
Hi @coldtelling,

I'd need the output of the following commands (run after the VPN connection is established, with vpnfailsafe in use) to investigate this:
* `ip route`
* `iptables -S`
* `resolvconf -l`
* `cat /etc/resolv.conf`
* `resolvconf --version`

Also, please add `set -x` in the second line of the script and include the output, like in your initial report.

If you're not using the latest version of vpnfailsafe, please update before testing.

The one obvious issue I see in the output you pasted is the `Too few arguments.` line, which is most likely produced by `resolvconf`. Please make sure you're using a recent version, that supports the `-x` switch (see: [here](https://github.com/wknapik/vpnfailsafe#user-content-what-are-the-requirementsassumptionslimitations-) for more info about the resolvconf/openresolv package requirements).

Feel free to make the info I asked for available any way that's convenient to you. If you're concerned about privacy, you can contact me at wmknapik at gmail. My PGP key signature is in my github account info, if you'd like to use PGP.

**Comment by wknapik** [comment]
Also, note that your firewall rules refer to device `tun0`, while the OpenVPN output indicates that `tun1` is in use.

**Comment by wknapik** [comment]
Hey @coldtelling. Any news ? Did you manage to resolve your problem ?

**Comment by wknapik** [comment]
No response for over a month, closing.
