### ISSUE TITLE
systemd-networkd /etc/hosts not being updated with the vpn server IP/DNS

### ISSUE THREAD

**Issue by ghost** [wknapik/vpnfailsafe#33]
Hi wknapik,

it's me again, hope you are doing well. 

I've recently switched from using networkmanager and a dispatcher to just systemd-networkd with the openvpn service started at boot but I am having issues with vpnfilesafe and was wondering if you have ever encountered something like this (as I am having trouble figuring out what is going on).

The main issue appears to be the vpnfailsafe not inserting the vpn remote address into the /etc/hosts so when the connection goes down (say I am coming back from sleep) I am unable to connect back to the vpn unless I clear the iptables rules.

I am running arch linux with systemd-networkd and systemd-resolved and both the iptables rules and the /etc/resolved.conf are correctly updated by your script.

The args passed to the vpnfailsafe on up/down are the following:
tun0
1500
1553
XX.XX.16.5
255.255.252.0
init

and from what I can tell the vpnfailsafe never goes into this:
if remote_entries="$(getent -s dns hosts "${cnf_remote_domains[@]}"|grep -v :)"; then

I am puzzled, any help would be really appreciated :)

Thank you

**Comment by ghost** [comment]
Some progress on this (that makes me even more confused) changing **line 37** from:

if remote_entries="$(**getent -s dns hosts** "${cnf_remote_domains[@]}"|grep -v :)"; then

to 

if remote_entries="$(**getent hosts** "${cnf_remote_domains[@]}"|grep -v :)"; then

seems to fix the issue, but I am wondering why was this working when I was using network manager?

"getent -s dns hosts" is definitely returning nothing while getent hosts is returning the /etc/hosts entries.

**Comment by ghost** [comment]
After spending a few more hours trying to get this sorted I ended up realizing that (IMHO) plain systemd-networkd is not really that elegant of a solution to deal with networks. I wanted to drop networkmanager for quite some time but not having a networkd-dispatcher in the base repository on Arch is not helping. if you have both wifi and eth on your machine you end up using timeouts and network-wait-online that again feels to me like a bad approach. Also without a dispatcher a hook coming back from sleep is the only option I could find. I am sure someone else can find a better solution but definitely not for me.

I just wanted to mention this in case anyone else is trying to get the same setup working and hitting the same issues.

I ended up switching to netctl/wpa_supplicant that is in the base repo in arch and has hooks built in. VPNFAILSAFE works out of the box without having to change the line above and I am much happier than when using networkmanager.

I'll keep this open just in case wknapik would like to dig into the issue above (if so let me know if I can be of any help).

Thank you

**Comment by wknapik** [comment]
Hey @bashruleseverythingaroundme. Sorry for the late reply. I haven't used systemd-{networkd,resolved} myself, but I just read the man page for systemd-resolved to reply in another issue and I think that's where the answer lies - take a look at  `man systemd-resolved`, especially section `/ETC/RESOLV.CONF` at the bottom. If you no longer care about getting this to work, we can just drop it, but if you do, let's start with `ls -l /etc/resolv.conf` - is it a regular file, or a symlink ?
