### ISSUE TITLE
systemd-resolved compatibility?

### ISSUE THREAD

**Issue by dpantel** [wknapik/vpnfailsafe#34]
Are there plans to support systemd-resolved?

Sorry, I am not too knowledgeable in this realm, but from some googling, it seems that systemd-resolved is supposed to supplant resolvconf and while the two can coexist, there might be issues.

Thoughts?

**Comment by wknapik** [comment]
Hi @dpantel,

The man page for systemd-resolved says:

> To improve compatibility, /etc/resolv.conf is read in order to discover configured system DNS servers, but only if it is not a symlink to /run/systemd/resolve/stub-resolv.conf, /usr/lib/systemd/resolv.conf or /run/systemd/resolve/resolv.conf (see below).

(section `/ETC/RESOLV.CONF` at the bottom goes into more detail)

So systemd-resolved can be used with vpnfailsafe. I'll close this issue, since there's nothing to fix, but if you run into a specific problem, feel free to open a new one.

**Comment by dpantel** [comment]
I think it’s more fair to say that vpnfailsafe might coexist and possibly not break systemd-resolvd, not that it actually works with it.

My question was whether you will switch from openresolv/resolvconf to systemd-resolvd, and it seems that the answer is “no”.

Thank you for the scripts anyway. It has been helpful as a guide.

**Comment by ammgws** [comment]
If you install systemd-resolvconf it creates a symlink at /usr/bin/resolvconf so this script should still work. (That is assuming the systemd implementation/interface is the same)

Have you tried it?

**Comment by dpantel** [comment]
Interesting point. I don’t remember if I’ve tried it. I’ll give it a go.

**Comment by wknapik** [comment]
@dpantel I can't see a reason to switch from openresolv to something systemd-specific. `man systemd-resolved` says that if /etc/resolv.conf is a regular file, it is read by systemd-resolved to discover DNS servers and it can be managed by tools/services predating (or just not explicitly supporting) systemd.

I'm not familiar with systemd-resolvconf, but that sounds like another option.
