### ISSUE TITLE
Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by askgitquestions** [wknapik/vpnfailsafe#37]
Does vpnfailsafe work for Ubuntu 18.04 LTS without any issues?
I asking this because they replaced ifupdown, resolvconf, and others with networkd, resolved, and their homegrown netplan. 
Can anyone using vpnfailsafe confirm that it works on Ubuntu 18.04 LTS without issues?

**Comment by ammgws** [comment]
Did you get anywhere with this?

**Comment by wknapik** [comment]
Hi @askgitquestions. I don't use Ubuntu, or any of these services, so I can't answer that. If you encounter any problems with this setup, please report them.
