### ISSUE TITLE
Rewrite using nftables

### ISSUE THREAD

**Issue by dngray** [wknapik/vpnfailsafe#38]
It seems that [nftables](https://en.wikipedia.org/wiki/Nftables) is certainly going to be the future.

I think this could drastically simplify things too, especially when considering IPv6 support https://github.com/wknapik/vpnfailsafe/issues/10

Should also be noted that a couple of major distributions are now using nftables by default:

- **Debian 10** https://wiki.debian.org/nftables
  > NOTE: Debian Buster uses the nftables framework by default.
  > 
  > Starting with Debian Buster, nf_tables is the default backend when using iptables, by means of the iptables-nft layer (i.e, using iptables syntax with the nf_tables kernel subsystem). This also affects ip6tables, arptables and ebtables.

- **RHEL 8** https://www.redhat.com/en/blog/using-nftables-red-hat-enterprise-linux-8
  > In Red Hat Enterprise Linux 8 the preferred low level firewall solution is nftables. This post is an introduction to using nftables. This is most relevant for system administrators and DevOps practitioners. Where it makes sense we will highlight differences between nftables and its predecessor iptables.

- [Fedora 32 Looking At Switching Firewalld From Iptables To Nftables (Phoronix)](https://www.phoronix.com/scan.php?page=news_item&px=Fedora-32-Firewalld-Nftables)

More information can be found [nftables (archwiki)](https://wiki.archlinux.org/index.php/Nftables) [nftables (gentoo)](https://wiki.gentoo.org/wiki/Nftables). Seems to be [available for alplinelinux](https://git.alpinelinux.org/aports/tree/main/nftables/APKBUILD) too.

**Comment by wknapik** [comment]
Hey @dngray. We talked elsewhere, so I won't repeat it all here. The tl;dr, for anyone interested, is that this would be too big a change for too little gain, so that is unlikely to happen. Closing for now.
