### ISSUE TITLE
Custom DNS

### ISSUE THREAD

**Issue by travankor** [wknapik/vpnfailsafe#39]
Not sure if this is in scope, but would it be possible to route a custom DNS protocol, like DNSCrypt (supports both authenticated and anonymized DNS), over the tunnel? Or have something like described in [this guide](https://docs.pi-hole.net/guides/vpn/dual-VPN/)?

This could also be useful for the DNS-over-HTTPS and DNS-over-TLS protocols. These protocols only support authentication, no anonymization, though.

**Comment by wknapik** [comment]
Hi @travankor,

I don't see how vpnfailsafe could be modified to facilitate the use of these protocols.

vpnfailsafe works only with OpenVPN and all OpenVPN does, with regard to name resolution, is push/pull IPs of DNS servers.

vpnfailsafe uses /etc/resolv.conf (via openresolv/resolvconf) to modify system-wide DNS settings. I'm guessing every "alternative" resolver implements compatibility with /etc/resolv.conf, one way, or another.

And on top of that, we're now seeing name resolution being done in applications, bypassing the system resolver altogether (DoH in Chrome and Firefox).

For now, there's nothing to do.
