### ISSUE TITLE
Support for TAP device

### ISSUE THREAD

**Issue by ch9PcB** [wknapik/vpnfailsafe#4]
Hello,

Would it be possible for vpnfailsafe.sh to work with TAP device as well?

Thanks for your work on a fine script.

**Comment by wknapik** [comment]
Just tested one tap-based VPN. Everything's working fine... It may be that the problems you reported were due to something else. Let's continue in the original issue...

**Comment by wknapik** [comment]
Ok, I've tested vpnfailsafe with >120 tap-based VPN servers in >70 cities/50 countries (from one VPN provider) and they all worked. I'm pretty sure the problems you experienced were not caused by the VPN being tap-based. Let's continue in the original issue.
