### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by ch9PcB** [wknapik/vpnfailsafe#5]
Hello

It would be wonderful if vpnfailsafe.sh could be made to work on OpenBSD.

Thanks in advance for your time and effort.

**Comment by wknapik** [comment]
This seems very unlikely to ever be implemented. Too much Linux-specific stuff. Closing, sorry.

**Comment by dngray** [comment]
Might be worth considering this port https://github.com/giovanifss/vpnfailsafe-openbsd
