### ISSUE TITLE
Antergos arch based system

### ISSUE THREAD

**Issue by GusRath** [wknapik/vpnfailsafe#6]
I have tried your script today, installed from AUR. I'm running airvpn on the command line. When  I connect to the server it seems nothing is happening. I mean nothing saved in /etc/hosts, /etc/resolv.conf  is not updated, neither my iptables rules. But no errors in the console when I 'm connecting to my VPN, and no sign of vpnfailsafe on stdout. When I run the script alone it reports an error : ./vpnfailsafe.sh: ligne 26: untrusted_ip : variable sans liaison (variable without link), but maybe it's normal. T
[Wed Nov 30 20:59:00 2016 OpenVPN 2.3.13 x86_64.txt](https://github.com/wknapik/vpnfailsafe/files/623022/Wed.Nov.30.20.59.00.2016.OpenVPN.2.3.13.x86_64.txt)
My interface is dev tun. 
I have modified my connection scripts to include vpnfaisafe, so can you tell me what I did wrong ?

**Comment by wknapik** [comment]
Hi Gus. It seems from the log you attached, that vpnfailsafe.sh is not being executed at all. Are you sure your config file contains the [necessary entries](https://github.com/wknapik/vpnfailsafe#how-do-i-installuse-it-) for vpnfailsafe ? Please paste/attach your config and the command line you're using to start OpenVPN. You can of course ommit any keys, or information you'd rather not share publicly from the config.

**Comment by GusRath** [comment]
Here is my command line : 
sudo openvpn --config .ovpnAirVPN_United-Kingdom_UDP-443
Here is my connection config file :
[AirVPN_Switzerland_UDP-443.txt](https://github.com/wknapik/vpnfailsafe/files/623083/AirVPN_Switzerland_UDP-443.txt)

**Comment by GusRath** [comment]
I'm sorry, I closed and reopen the issue

**Comment by wknapik** [comment]
The file looks fine, but I noticed you're using the config for the UK in your OpenVPN invocation and the config file you attached is for Switzerland. That would explain why vpnfailsafe is not being executed - the config for the UK probably doesn't refer to vpnfailsafe. Is that the issue here ?

**Comment by GusRath** [comment]
No, no it's OK . I'm running different servers but all have these lines 👍 
script-security 2
up /etc/openvpn/vpnfailsafe.sh
down /etc/openvpn/vpnfailsafe.sh
And the vpnfailsafe script is present in the right place.
I don'nt understand why the script is not executed.
Anyway thank you so much for your help !

**Comment by wknapik** [comment]
Well, let's not give up right away. There's probably a simple explanation. Let me try a few things, maybe I'll come up with something...

**Comment by GusRath** [comment]
I was used to Sysv init scripts (ifup, ifdown) and systemd is a bit new for me. I even do not know how to manage this in Archlinux (or Antergos).

**Comment by wknapik** [comment]
The config and the log don't point to any obvious problems (other than the bizarre config filename with the extension at the beginning). I thought I could get a trial account at AirVPN to test this myself, but those are not available automatically (you have to send an email requesting one).

I assume OpenVPN would complain if it couldn't execute the script for whatever reason, so that's probably not it.

Have you tried using a test script, that just prints some text to stdout, in place of vpnfailsafe ? If that works, you could rename it to /etc/openvpn/vpnfailsafe.sh and see what happens. Work it out from there...

As for systemd - yeah, it's a shame all distros followed red hat and jumped off that cliff, but we have to live with it now. You can start your VPN tunnel by placing a modified version of /usr/lib/systemd/system/openvpn@.service in /etc/systemd/system/multi-user.target.wants/ under an appropriate name. The details are easily googlable.

Let's keep this issue open. I'll try to get that trial.

**Comment by GusRath** [comment]
I have tried your trick replacing vpnfailsafe.sh with a script printing Hello! on stdout but nothing new is echoed, so I deleted the script file, keeping the line that invoke it and openvpn is not complaining.
So ?

**Comment by GusRath** [comment]
I just find a simple solution in adding --script-security 2 --up /etc/openvpn/vpnfailsafe.sh at the end of my command line (sudo openvpn --config .....). Apparently the script when invoked in the config file do not run.
I'll have to create an alias  if I do not want to fall asleep during typing the connection line. Thank you for all

**Comment by GusRath** [comment]
Another issue happened 👍 
RTNETLINK answers: File exists
Thu Dec  1 00:04:55 2016 ERROR: Linux route add command failed: external program exited with error status: 2
when run the connection command.

**Comment by wknapik** [comment]
The second thing is not a problem, as explained [here](https://github.com/wknapik/vpnfailsafe#what-are-the-requirementsassumptionslimitations-). 

But the behavior of OpenVPN on your box is weird. I'm running what seems to be the exact same package and when I configure a non-existent up/down script, or one that's not executable, OpenVPN exits immediately after starting, with an accurate error message. That doesn't happen on your machine... Have you tried different locations for those files ? Maybe on another filesystem ?
And properly configured scripts are not executed at all ? This is really strange.

You could `strace` OpenVPN and see what it's actually doing when an up/down script is supposed to be executed, or just [report a bug against OpenVPN](https://community.openvpn.net/openvpn/report), including the "hello world" testcase (the site seems to be down at the moment ;/).

**Comment by wknapik** [comment]
What does `which openvpn` say ?

**Comment by GusRath** [comment]
which openvpn
/usr/bin/openvpn
I don't know if you really understood what I explained in my previous comments (maybe my explanations are not so clear!). The script is run only if I add *--script-security 2 --up /etc/openvpn/vpnfailsafe.sh* at the end of the command line for connecting to vpn server. None of the scripts called in server.ovpn are run with no complaint from openvpn when they are not present. Logically it's normal for *up* script because the tun0 connection must be established before the script is run. But for the *down* script I did not find  a way to call it yet. More surprising if I stop the vpn connection when I connect with *--script-security 2 --up /etc/openvpn/vpnfailsafe.sh* option Internet is no more accessible.

**Comment by GusRath** [comment]
By the way my box is a new one with a fresh install of Antergos and openvpn 2.3.13-1. No mess. Thank you again for your help.

**Comment by wknapik** [comment]
No problem GusRath.

What I meant was, that it should work with up/down scripts configured in the config file. There should be no need to pass that on the command line. It seems like an OpenVPN bug, or an issue with the OpenVPN build in your distro, or (most likely) the environment. But since you're using those command line options anyway - you can (and should) pass both the --up and --down options at the same time:
```
openvpn --script-security 2 --up /etc/openvpn/vpnfailsafe.sh --down /etc/openvpn/vpnfailsafe.sh --config your_config_file
```

**Comment by GusRath** [comment]
Hello wknapik.
This morning I tried to run vpnfailsafe script from within the config file and it works! Didn't change anything since last night. Just rebooting my PC. I am keeping some errors when vpnfailsafe is running */usr/bin/ip route add* but your program is working fine : no more internet when vpn is down. I attach the console messages of openvpn. Can you tell me if these errors are significant, (I guess so) ?

**Comment by GusRath** [comment]
[openvpnStdout.txt](https://github.com/wknapik/vpnfailsafe/files/623950/openvpnStdout.txt)

**Comment by wknapik** [comment]
Hi Gus. I'm glad things are working for you. As [mentioned](https://github.com/wknapik/vpnfailsafe#what-are-the-requirementsassumptionslimitations-) in the README, the RTNETLINK errors are nothing to worry about:
> "RTNETLINK answers: File exists" errors can be ignored safely. They appear when OpenVPN tries to set up a route, that's already been created by `vpnfailsafe`. Adding the "route-noexec" option will tell OpenVPN to leave routing to `vpnfailsafe` and prevent those errors from appearing.

You can suppress them, or just leave your config as-is - either way vpnfailsafe is working correctly :)

**Comment by GusRath** [comment]
I'd like to tell you how your help was great for me. Have a nice day.

**Comment by wknapik** [comment]
Thanks GusRath :) Glad I could help :)
